.TH "com.example.demo.DemoApplication" 3 "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.demo.DemoApplication \- main класс, используемый при запуске приложения  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.RI "Главный метод вызываемый при запуске приложения "
.in -1c
.SH "Detailed Description"
.PP 
main класс, используемый при запуске приложения 
.PP
Definition at line \fB9\fP of file \fBDemoApplication\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.example\&.demo\&.DemoApplication\&.main (String[] args)\fR [static]\fP"

.PP
Главный метод вызываемый при запуске приложения 
.PP
\fBParameters\fP
.RS 4
\fIПринимает\fP на вход строковые параметры аргументов запуска 
.RE
.PP
\fBReturns\fP
.RS 4
Ничо не возвращает 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBDemoApplication\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
