.TH "com.example.demo" 3 "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.demo
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDemoApplication\fP"
.br
.RI "main класс, используемый при запуске приложения "
.ti -1c
.RI "class \fBMaterial\fP"
.br
.RI "Класс объекта материала, используемый при работе с базой данных "
.ti -1c
.RI "class \fBMaterialController\fP"
.br
.RI "Класс контроллера для обработки HTTP запросов "
.ti -1c
.RI "interface \fBMaterialRepository\fP"
.br
.RI "Репозиторий для работы с базой данных "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
