.TH "com.example.demo.Material" 3 "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.demo.Material \- Класс объекта материала, используемый при работе с базой данных  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetId\fP (Integer \fBid\fP)"
.br
.RI "сеттер для идентификатора "
.ti -1c
.RI "void \fBsetName\fP (String \fBname\fP)"
.br
.RI "сеттер для имени "
.ti -1c
.RI "Integer \fBgetId\fP ()"
.br
.RI "геттер для идентификатора "
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.RI "геттер для идентификатора "
.ti -1c
.RI "void \fBsetQuantity\fP (int i)"
.br
.RI "сеттер для количества "
.ti -1c
.RI "Integer \fBgetQuantity\fP ()"
.br
.RI "геттер для количества "
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.RI "перегруженный метод вывода в консоль "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Integer \fBid\fP"
.br
.RI "Идентификатор для первиного ключа "
.ti -1c
.RI "String \fBname\fP"
.br
.RI "название материала "
.ti -1c
.RI "int \fBquantity\fP"
.br
.RI "количество материала "
.in -1c
.SH "Detailed Description"
.PP 
Класс объекта материала, используемый при работе с базой данных 
.PP
Definition at line \fB15\fP of file \fBMaterial\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Integer com\&.example\&.demo\&.Material\&.getId ()"

.PP
геттер для идентификатора 
.PP
Definition at line \fB34\fP of file \fBMaterial\&.java\fP\&.
.SS "String com\&.example\&.demo\&.Material\&.getName ()"

.PP
геттер для идентификатора 
.PP
Definition at line \fB38\fP of file \fBMaterial\&.java\fP\&.
.SS "Integer com\&.example\&.demo\&.Material\&.getQuantity ()"

.PP
геттер для количества 
.PP
Definition at line \fB46\fP of file \fBMaterial\&.java\fP\&.
.SS "void com\&.example\&.demo\&.Material\&.setId (Integer id)"

.PP
сеттер для идентификатора 
.PP
Definition at line \fB26\fP of file \fBMaterial\&.java\fP\&.
.SS "void com\&.example\&.demo\&.Material\&.setName (String name)"

.PP
сеттер для имени 
.PP
Definition at line \fB30\fP of file \fBMaterial\&.java\fP\&.
.SS "void com\&.example\&.demo\&.Material\&.setQuantity (int i)"

.PP
сеттер для количества 
.PP
Definition at line \fB42\fP of file \fBMaterial\&.java\fP\&.
.SS "String com\&.example\&.demo\&.Material\&.toString ()"

.PP
перегруженный метод вывода в консоль 
.PP
Definition at line \fB51\fP of file \fBMaterial\&.java\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Integer com\&.example\&.demo\&.Material\&.id"

.PP
Идентификатор для первиного ключа 
.PP
Definition at line \fB20\fP of file \fBMaterial\&.java\fP\&.
.SS "String com\&.example\&.demo\&.Material\&.name"

.PP
название материала 
.PP
Definition at line \fB22\fP of file \fBMaterial\&.java\fP\&.
.SS "int com\&.example\&.demo\&.Material\&.quantity"

.PP
количество материала 
.PP
Definition at line \fB24\fP of file \fBMaterial\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
