.TH "com.example.demo.MaterialRepository" 3 "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.demo.MaterialRepository \- Репозиторий для работы с базой данных  

.SH SYNOPSIS
.br
.PP
.PP
Inherits JpaRepository< Material, Long >\&.
.SH "Detailed Description"
.PP 
Репозиторий для работы с базой данных 
.PP
Definition at line \fB7\fP of file \fBMaterialRepository\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
