.TH "src/main/java/com/example/demo/Material.java" 3 "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/com/example/demo/Material.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.example\&.demo\&.Material\fP"
.br
.RI "Класс объекта материала, используемый при работе с базой данных "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.example\&.demo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
