.TH "md__h_e_l_p" 3 "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__h_e_l_p \- Getting Started 
.PP
 
.SS "Reference Documentation"
For further reference, please consider the following sections:
.PP
.IP "\(bu" 2
\fROfficial Apache Maven documentation\fP
.IP "\(bu" 2
\fRSpring Boot Maven Plugin Reference Guide\fP
.IP "\(bu" 2
\fRCreate an OCI image\fP
.IP "\(bu" 2
\fRSpring Web\fP
.IP "\(bu" 2
\fRSpring Data JPA\fP
.PP
.SS "Guides"
The following guides illustrate how to use some features concretely:
.PP
.IP "\(bu" 2
\fRBuilding a RESTful Web Service\fP
.IP "\(bu" 2
\fRServing Web Content with Spring MVC\fP
.IP "\(bu" 2
\fRBuilding REST services with Spring\fP
.IP "\(bu" 2
\fRAccessing Data with JPA\fP 
.PP

